<h2>Se connecter avec un compte utilisateur</h2>

<form action="" method="post">
    <fieldset>
        <legend>Informations d'authentification</legend>
        <input type="text" placeholder="Votre email :"name="email">
        <input type="password" placeholder="Votre mot de passe :" name="pwd">
    <input type="submit" value="Connexion">
    <input type="reset" value="Annuler">
    
    </fieldset>
</form>