<table class="generic-table">
  <?php if(empty($basketItems) == true): ?>
  <tr>
    <td>Votre panier est vide</td>
  </tr>
  <?php else:?>
  <thead>
    <tr>
      <th>Quantité</th>
      <th>Produit</th>
      <th>Prix Unitaire</th>
      <th>Prix Total</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($basketItems as $basketItem): ?>
    <tr>
      <td><?= $basketItem['quantityOrder'] ?></td>
      <td><?= $basketItem['name'] ?></td>
      <td><?= $basketItem['priceEach'] ?></td>
      <td><?= $basketItem['priceEach'] * $basketItem['quantityOrder'] ?></td>
      <td><i data-id="<?= $basketItem['mealId'] ?>" class="fas fa-trash-alt remove-order"></i></td>
    </tr>
  <?php endforeach ?>
  </tbody>
  <?php endif ?>
</table>
