<thead>
  <tr>
    <th>Quantité</th>
    <th>Produit</th>
    <th>Prix Unitaire</th>
    <th>Prix Total</th>
  </tr>
</thead>
<tbody>
  <?php foreach ($basketLists as $basketList): ?>
  <tr>
    <td><?= $basketList['quantityOrder'] ?></td>
    <td><?= $basketList['name'] ?></td>
    <td><?= $basketList['priceEach'] ?></td>
    <td><?= $basketList['priceEach'] * $basketList['quantityOrder'] ?></td>
    <td><i id="<?= $basketList['orderId'] ?>" class="fas fa-trash-alt remove-order"></i></td>
  </tr>
<?php endforeach ?>
</tbody>
