<!-- Message de notification -->

<!-- Code HTML à écrire -->

<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
      <?php foreach($mealObjects as $mealObject): ?>
        <tr>
          <td><img src="<?= $wwwUrl ?>/images/meals/<?= $mealObject["Photo"] ?>"  alt=""></td>
          <td><h4><?= $mealObject["Name"] ?></h4><p><?= $mealObject["Description"] ?></p></td>
          <td><h4><?= number_format($mealObject["SalePrice"], 2) ?> €</h4></td>
        </tr>
      <?php endforeach; ?>
    </tbody>
</table>
