<h2>Réservation d'une table</h2>

<form action="<?= $requestUrl ?>/Booking" method="post" class="generic-form">
  <fieldset>
    <legend>Informations</legend>
    <label>Date de réservation :</label>

    <input type="hidden" name="bookingCurrentUser" value="24">

    <select name="bookingDay">
        <option value="">---Selectionnez un jour---</option>
      <?php for($i = 1; $i < 32; $i++): ?>
        <option value="<?= $i ?>"><?= $i ?></option>
      <?php endfor; ?>
    </select>

    <span> / <span>

    <select name="bookingMonth">
      <option value="">---Selectionnez un mois---</option>
      <option value="01">Janvier</option>
      <option value="02">Février</option>
      <option value="03">Mars</option>
      <option value="04">Avril</option>
      <option value="05">Mai</option>
      <option value="06">Juin</option>
      <option value="07">Juillet</option>
      <option value="08">Août</option>
      <option value="09">Septembre</option>
      <option value="10">Octobre</option>
      <option value="11">Novembre</option>
      <option value="12">Décembre</option>
    </select>

    <span> / <span>

    <select name="bookingYear">
      <option value="">---Selectionnez une année---</option>
      <?php for($i = 2018; $i < 2025; $i++): ?>
        <option value="<?= $i ?>"><?= $i ?></option>
      <?php endfor; ?>
    </select>

    <span> à <span>

    <select name="bookingHour">
      <option value="">---Selectionnez une heure---</option>
      <?php for($i = 0; $i < 10; $i++): ?>
        <option value="0<?= $i ?>">0<?= $i ?></option>
      <?php endfor; ?>
      <?php for($i = 10; $i < 24; $i++): ?>
        <option value="<?= $i ?>"><?= $i ?></option>
      <?php endfor; ?>
    </select>

    <span>:<span>

    <select name="bookingMinute">
      <option value="">---Selectionnez les minutes---</option>
      <?php for($i = 0; $i < 10; $i++): ?>
        <option value="0<?= $i ?>">0<?= $i ?></option>
      <?php endfor; ?>
      <?php for($i = 10; $i < 60; $i++): ?>
        <option value="<?= $i ?>"><?= $i ?></option>
      <?php endfor; ?>
    </select>

    <label>Nombre de couverts :</label>
    <select name="bookingSeat">
      <?php for($i = 0; $i < 9; $i++): ?>
        <option value="<?= $i ?>"><?= $i ?></option>
      <?php endfor; ?>
    </select>
  </fieldset>
  <input type="submit" value="Réserver" class="button button-primary">
  <input type="reset" value="Annuler" class="button button-cancel">
</form>
